### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by ghost** [sudeephazra/perl-on-netbeans#4]
When I install plugin I have :

Some plugins require the Java platform in version Java > 10
The Java platform version Java > 10 was requested but only 1.8 is running.  The following plugin is affected:       Perl On NetBeans 
Some plugins require plugin File Templates to be installed.
The plugin File Templates is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Perl On NetBeans 
Some plugins require plugin MIME Lookup API to be installed.
The plugin MIME Lookup API is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Perl On NetBeans 
Some plugins require plugin External Execution Base API to be installed.
The plugin External Execution Base API is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Perl On NetBeans 
Some plugins require plugin External Execution API to be installed.
The plugin External Execution API is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Perl On NetBeans 
Some plugins require plugin Execution API to be installed.
The plugin Execution API is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Perl On NetBeans 
Some plugins require plugin File System API to be installed.
The plugin File System API is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Perl On NetBeans  Some plugins not installed to avoid potential installation problems.   Note: Missing modules may be published on Update Centers. Please run "Check for Newest" from the "Available Plugins" tab.

I'm on Apache NetBeans IDE 12.0

Thanks
Thomas

**Comment by sudeephazra** [comment]
The plugin currently does not support Netbeans 12. For the supported platforms please see http://plugins.netbeans.org/plugin/36183/

**Comment by ghost** [comment]
Do you think it will support Netbeans 12 ?

**Comment by sudeephazra** [comment]
@guenneguezt  Surely it will support Netbeans 12 but I cannot guarantee on the timelines, as of now.

**Comment by ghost** [comment]
Thanks for answear.
is there à way to be notidy when it will be supporte ?

**Comment by sudeephazra** [comment]
Yes surely, you can follow on Twitter https://twitter.com/perlonnetbeans and Facebook https://www.facebook.com/PerlOnNetBeans to stay updated.
