### ISSUE TITLE
Manually install Perl on NetBeans IDE 

### ISSUE THREAD

**Issue by eddietorial** [sudeephazra/perl-on-netbeans#5]
Hey Sudeep, I am a beginner with Perl. I use Netbeans 12.3 on FreeBSD 13. I do not see Perl on NetBeans IDE listed in Tools>Plugins. Is there a link from where I can download and manually install it? Thanks!

**Comment by sudeephazra** [comment]
The plugin is not available for Netbeans 12 yet. Please watch out for the Facebook and Twitter pages for updates. #KeepPerlin https://twitter.com/perlonnetbeans https://www.facebook.com/PerlOnNetBeans
